// Seed data for the team_aliases table (§10.3). Not exhaustive — admins can
// add rows for gaps the parser/matcher surfaces (e.g. a new capper using a
// nickname not listed here). Covers the leagues named in BUILD_SPEC.md §6/§11.

export interface TeamAliasSeed {
  league: string;
  canonical: string;
  aliases: string[];
}

export const TEAM_ALIASES: TeamAliasSeed[] = [
  // ---------------------------------------------------------------- NFL
  { league: "NFL", canonical: "Arizona Cardinals", aliases: ["Cardinals", "Cards", "ARI", "AZ"] },
  { league: "NFL", canonical: "Atlanta Falcons", aliases: ["Falcons", "ATL"] },
  { league: "NFL", canonical: "Baltimore Ravens", aliases: ["Ravens", "BAL"] },
  { league: "NFL", canonical: "Buffalo Bills", aliases: ["Bills", "BUF"] },
  { league: "NFL", canonical: "Carolina Panthers", aliases: ["Panthers", "CAR"] },
  { league: "NFL", canonical: "Chicago Bears", aliases: ["Bears", "CHI"] },
  { league: "NFL", canonical: "Cincinnati Bengals", aliases: ["Bengals", "CIN"] },
  { league: "NFL", canonical: "Cleveland Browns", aliases: ["Browns", "CLE"] },
  { league: "NFL", canonical: "Dallas Cowboys", aliases: ["Cowboys", "DAL"] },
  { league: "NFL", canonical: "Denver Broncos", aliases: ["Broncos", "DEN"] },
  { league: "NFL", canonical: "Detroit Lions", aliases: ["Lions", "DET"] },
  { league: "NFL", canonical: "Green Bay Packers", aliases: ["Packers", "GB", "Green Bay"] },
  { league: "NFL", canonical: "Houston Texans", aliases: ["Texans", "HOU"] },
  { league: "NFL", canonical: "Indianapolis Colts", aliases: ["Colts", "IND"] },
  { league: "NFL", canonical: "Jacksonville Jaguars", aliases: ["Jaguars", "Jags", "JAX"] },
  { league: "NFL", canonical: "Kansas City Chiefs", aliases: ["Chiefs", "KC", "Kansas City"] },
  { league: "NFL", canonical: "Las Vegas Raiders", aliases: ["Raiders", "LV", "Vegas"] },
  { league: "NFL", canonical: "Los Angeles Chargers", aliases: ["Chargers", "LAC"] },
  { league: "NFL", canonical: "Los Angeles Rams", aliases: ["Rams", "LAR"] },
  { league: "NFL", canonical: "Miami Dolphins", aliases: ["Dolphins", "MIA"] },
  { league: "NFL", canonical: "Minnesota Vikings", aliases: ["Vikings", "MIN"] },
  { league: "NFL", canonical: "New England Patriots", aliases: ["Patriots", "Pats", "NE"] },
  { league: "NFL", canonical: "New Orleans Saints", aliases: ["Saints", "NO"] },
  { league: "NFL", canonical: "New York Giants", aliases: ["Giants", "NYG"] },
  { league: "NFL", canonical: "New York Jets", aliases: ["Jets", "NYJ"] },
  { league: "NFL", canonical: "Philadelphia Eagles", aliases: ["Eagles", "PHI"] },
  { league: "NFL", canonical: "Pittsburgh Steelers", aliases: ["Steelers", "PIT"] },
  { league: "NFL", canonical: "San Francisco 49ers", aliases: ["49ers", "Niners", "SF"] },
  { league: "NFL", canonical: "Seattle Seahawks", aliases: ["Seahawks", "Hawks", "SEA"] },
  { league: "NFL", canonical: "Tampa Bay Buccaneers", aliases: ["Buccaneers", "Bucs", "TB"] },
  { league: "NFL", canonical: "Tennessee Titans", aliases: ["Titans", "TEN"] },
  { league: "NFL", canonical: "Washington Commanders", aliases: ["Commanders", "WAS"] },

  // ---------------------------------------------------------------- NBA
  { league: "NBA", canonical: "Atlanta Hawks", aliases: ["Hawks", "ATL"] },
  { league: "NBA", canonical: "Boston Celtics", aliases: ["Celtics", "BOS"] },
  { league: "NBA", canonical: "Brooklyn Nets", aliases: ["Nets", "BKN"] },
  { league: "NBA", canonical: "Charlotte Hornets", aliases: ["Hornets", "CHA"] },
  { league: "NBA", canonical: "Chicago Bulls", aliases: ["Bulls", "CHI"] },
  { league: "NBA", canonical: "Cleveland Cavaliers", aliases: ["Cavaliers", "Cavs", "CLE"] },
  { league: "NBA", canonical: "Dallas Mavericks", aliases: ["Mavericks", "Mavs", "DAL"] },
  { league: "NBA", canonical: "Denver Nuggets", aliases: ["Nuggets", "DEN"] },
  { league: "NBA", canonical: "Detroit Pistons", aliases: ["Pistons", "DET"] },
  { league: "NBA", canonical: "Golden State Warriors", aliases: ["Warriors", "GSW", "Golden State"] },
  { league: "NBA", canonical: "Houston Rockets", aliases: ["Rockets", "HOU"] },
  { league: "NBA", canonical: "Indiana Pacers", aliases: ["Pacers", "IND"] },
  { league: "NBA", canonical: "LA Clippers", aliases: ["Clippers", "LAC"] },
  { league: "NBA", canonical: "Los Angeles Lakers", aliases: ["Lakers", "LAL"] },
  { league: "NBA", canonical: "Memphis Grizzlies", aliases: ["Grizzlies", "MEM"] },
  { league: "NBA", canonical: "Miami Heat", aliases: ["Heat", "MIA"] },
  { league: "NBA", canonical: "Milwaukee Bucks", aliases: ["Bucks", "MIL"] },
  { league: "NBA", canonical: "Minnesota Timberwolves", aliases: ["Timberwolves", "Wolves", "MIN"] },
  { league: "NBA", canonical: "New Orleans Pelicans", aliases: ["Pelicans", "NOP"] },
  { league: "NBA", canonical: "New York Knicks", aliases: ["Knicks", "NYK"] },
  { league: "NBA", canonical: "Oklahoma City Thunder", aliases: ["Thunder", "OKC"] },
  { league: "NBA", canonical: "Orlando Magic", aliases: ["Magic", "ORL"] },
  { league: "NBA", canonical: "Philadelphia 76ers", aliases: ["76ers", "Sixers", "PHI"] },
  { league: "NBA", canonical: "Phoenix Suns", aliases: ["Suns", "PHX"] },
  { league: "NBA", canonical: "Portland Trail Blazers", aliases: ["Trail Blazers", "Blazers", "POR"] },
  { league: "NBA", canonical: "Sacramento Kings", aliases: ["Kings", "SAC"] },
  { league: "NBA", canonical: "San Antonio Spurs", aliases: ["Spurs", "SAS"] },
  { league: "NBA", canonical: "Toronto Raptors", aliases: ["Raptors", "TOR"] },
  { league: "NBA", canonical: "Utah Jazz", aliases: ["Jazz", "UTA"] },
  { league: "NBA", canonical: "Washington Wizards", aliases: ["Wizards", "WAS"] },

  // ---------------------------------------------------------------- MLB
  { league: "MLB", canonical: "Arizona Diamondbacks", aliases: ["Diamondbacks", "D-backs", "ARI"] },
  { league: "MLB", canonical: "Atlanta Braves", aliases: ["Braves", "ATL"] },
  { league: "MLB", canonical: "Baltimore Orioles", aliases: ["Orioles", "O's", "BAL"] },
  { league: "MLB", canonical: "Boston Red Sox", aliases: ["Red Sox", "BOS"] },
  { league: "MLB", canonical: "Chicago Cubs", aliases: ["Cubs", "CHC"] },
  { league: "MLB", canonical: "Chicago White Sox", aliases: ["White Sox", "CWS"] },
  { league: "MLB", canonical: "Cincinnati Reds", aliases: ["Reds", "CIN"] },
  { league: "MLB", canonical: "Cleveland Guardians", aliases: ["Guardians", "CLE"] },
  { league: "MLB", canonical: "Colorado Rockies", aliases: ["Rockies", "COL"] },
  { league: "MLB", canonical: "Detroit Tigers", aliases: ["Tigers", "DET"] },
  { league: "MLB", canonical: "Houston Astros", aliases: ["Astros", "HOU"] },
  { league: "MLB", canonical: "Kansas City Royals", aliases: ["Royals", "KC"] },
  { league: "MLB", canonical: "Los Angeles Angels", aliases: ["Angels", "LAA"] },
  { league: "MLB", canonical: "Los Angeles Dodgers", aliases: ["Dodgers", "LAD"] },
  { league: "MLB", canonical: "Miami Marlins", aliases: ["Marlins", "MIA"] },
  { league: "MLB", canonical: "Milwaukee Brewers", aliases: ["Brewers", "MIL"] },
  { league: "MLB", canonical: "Minnesota Twins", aliases: ["Twins", "MIN"] },
  { league: "MLB", canonical: "New York Mets", aliases: ["Mets", "NYM"] },
  { league: "MLB", canonical: "New York Yankees", aliases: ["Yankees", "NYY"] },
  { league: "MLB", canonical: "Oakland Athletics", aliases: ["Athletics", "A's", "OAK"] },
  { league: "MLB", canonical: "Philadelphia Phillies", aliases: ["Phillies", "PHI"] },
  { league: "MLB", canonical: "Pittsburgh Pirates", aliases: ["Pirates", "PIT"] },
  { league: "MLB", canonical: "San Diego Padres", aliases: ["Padres", "SD"] },
  { league: "MLB", canonical: "San Francisco Giants", aliases: ["Giants", "SF"] },
  { league: "MLB", canonical: "Seattle Mariners", aliases: ["Mariners", "SEA"] },
  { league: "MLB", canonical: "St. Louis Cardinals", aliases: ["Cardinals", "Cards", "STL"] },
  { league: "MLB", canonical: "Tampa Bay Rays", aliases: ["Rays", "TB"] },
  { league: "MLB", canonical: "Texas Rangers", aliases: ["Rangers", "TEX"] },
  { league: "MLB", canonical: "Toronto Blue Jays", aliases: ["Blue Jays", "Jays", "TOR"] },
  { league: "MLB", canonical: "Washington Nationals", aliases: ["Nationals", "Nats", "WSH"] },

  // ---------------------------------------------------------------- NHL
  { league: "NHL", canonical: "Anaheim Ducks", aliases: ["Ducks", "ANA"] },
  { league: "NHL", canonical: "Utah Hockey Club", aliases: ["Utah", "UTA"] },
  { league: "NHL", canonical: "Boston Bruins", aliases: ["Bruins", "BOS"] },
  { league: "NHL", canonical: "Buffalo Sabres", aliases: ["Sabres", "BUF"] },
  { league: "NHL", canonical: "Calgary Flames", aliases: ["Flames", "CGY"] },
  { league: "NHL", canonical: "Carolina Hurricanes", aliases: ["Hurricanes", "Canes", "CAR"] },
  { league: "NHL", canonical: "Chicago Blackhawks", aliases: ["Blackhawks", "CHI"] },
  { league: "NHL", canonical: "Colorado Avalanche", aliases: ["Avalanche", "Avs", "COL"] },
  { league: "NHL", canonical: "Columbus Blue Jackets", aliases: ["Blue Jackets", "CBJ"] },
  { league: "NHL", canonical: "Dallas Stars", aliases: ["Stars", "DAL"] },
  { league: "NHL", canonical: "Detroit Red Wings", aliases: ["Red Wings", "DET"] },
  { league: "NHL", canonical: "Edmonton Oilers", aliases: ["Oilers", "EDM"] },
  { league: "NHL", canonical: "Florida Panthers", aliases: ["Panthers", "FLA"] },
  { league: "NHL", canonical: "Los Angeles Kings", aliases: ["Kings", "LAK"] },
  { league: "NHL", canonical: "Minnesota Wild", aliases: ["Wild", "MIN"] },
  { league: "NHL", canonical: "Montreal Canadiens", aliases: ["Canadiens", "Habs", "MTL"] },
  { league: "NHL", canonical: "Nashville Predators", aliases: ["Predators", "Preds", "NSH"] },
  { league: "NHL", canonical: "New Jersey Devils", aliases: ["Devils", "NJD"] },
  { league: "NHL", canonical: "New York Islanders", aliases: ["Islanders", "Isles", "NYI"] },
  { league: "NHL", canonical: "New York Rangers", aliases: ["Rangers", "NYR"] },
  { league: "NHL", canonical: "Ottawa Senators", aliases: ["Senators", "Sens", "OTT"] },
  { league: "NHL", canonical: "Philadelphia Flyers", aliases: ["Flyers", "PHI"] },
  { league: "NHL", canonical: "Pittsburgh Penguins", aliases: ["Penguins", "Pens", "PIT"] },
  { league: "NHL", canonical: "San Jose Sharks", aliases: ["Sharks", "SJS"] },
  { league: "NHL", canonical: "Seattle Kraken", aliases: ["Kraken", "SEA"] },
  { league: "NHL", canonical: "St. Louis Blues", aliases: ["Blues", "STL"] },
  { league: "NHL", canonical: "Tampa Bay Lightning", aliases: ["Lightning", "Bolts", "TBL"] },
  { league: "NHL", canonical: "Toronto Maple Leafs", aliases: ["Maple Leafs", "Leafs", "TOR"] },
  { league: "NHL", canonical: "Vancouver Canucks", aliases: ["Canucks", "VAN"] },
  { league: "NHL", canonical: "Vegas Golden Knights", aliases: ["Golden Knights", "VGK"] },
  { league: "NHL", canonical: "Washington Capitals", aliases: ["Capitals", "Caps", "WSH"] },
  { league: "NHL", canonical: "Winnipeg Jets", aliases: ["Jets", "WPG"] },

  // ---------------------------------------------------------------- EPL
  { league: "EPL", canonical: "Arsenal", aliases: ["Arsenal", "Gunners"] },
  { league: "EPL", canonical: "Aston Villa", aliases: ["Aston Villa", "Villa"] },
  { league: "EPL", canonical: "Bournemouth", aliases: ["Bournemouth"] },
  { league: "EPL", canonical: "Brentford", aliases: ["Brentford"] },
  { league: "EPL", canonical: "Brighton & Hove Albion", aliases: ["Brighton"] },
  { league: "EPL", canonical: "Burnley", aliases: ["Burnley"] },
  { league: "EPL", canonical: "Chelsea", aliases: ["Chelsea"] },
  { league: "EPL", canonical: "Crystal Palace", aliases: ["Crystal Palace", "Palace"] },
  { league: "EPL", canonical: "Everton", aliases: ["Everton"] },
  { league: "EPL", canonical: "Fulham", aliases: ["Fulham"] },
  { league: "EPL", canonical: "Leeds United", aliases: ["Leeds"] },
  { league: "EPL", canonical: "Liverpool", aliases: ["Liverpool"] },
  { league: "EPL", canonical: "Manchester City", aliases: ["Man City", "Manchester City"] },
  { league: "EPL", canonical: "Manchester United", aliases: ["Man United", "Man Utd", "Manchester United"] },
  { league: "EPL", canonical: "Newcastle United", aliases: ["Newcastle"] },
  { league: "EPL", canonical: "Nottingham Forest", aliases: ["Nottingham Forest", "Forest"] },
  { league: "EPL", canonical: "Sunderland", aliases: ["Sunderland"] },
  { league: "EPL", canonical: "Tottenham Hotspur", aliases: ["Tottenham", "Spurs"] },
  { league: "EPL", canonical: "West Ham United", aliases: ["West Ham"] },
  { league: "EPL", canonical: "Wolverhampton Wanderers", aliases: ["Wolves"] },

  // ---------------------------------------------------------------- LALIGA
  { league: "LALIGA", canonical: "Real Madrid", aliases: ["Real Madrid", "Madrid"] },
  { league: "LALIGA", canonical: "Barcelona", aliases: ["Barcelona", "Barca"] },
  { league: "LALIGA", canonical: "Atletico Madrid", aliases: ["Atletico Madrid", "Atletico", "Atleti"] },
  { league: "LALIGA", canonical: "Sevilla", aliases: ["Sevilla"] },
  { league: "LALIGA", canonical: "Real Betis", aliases: ["Real Betis", "Betis"] },
  { league: "LALIGA", canonical: "Real Sociedad", aliases: ["Real Sociedad", "Sociedad"] },
  { league: "LALIGA", canonical: "Villarreal", aliases: ["Villarreal"] },
  { league: "LALIGA", canonical: "Athletic Bilbao", aliases: ["Athletic Bilbao", "Bilbao"] },
  { league: "LALIGA", canonical: "Valencia", aliases: ["Valencia"] },
  { league: "LALIGA", canonical: "Celta Vigo", aliases: ["Celta Vigo", "Celta"] },
  { league: "LALIGA", canonical: "Osasuna", aliases: ["Osasuna"] },
  { league: "LALIGA", canonical: "Getafe", aliases: ["Getafe"] },
  { league: "LALIGA", canonical: "Girona", aliases: ["Girona"] },
  { league: "LALIGA", canonical: "Las Palmas", aliases: ["Las Palmas"] },
  { league: "LALIGA", canonical: "Mallorca", aliases: ["Mallorca"] },
  { league: "LALIGA", canonical: "Rayo Vallecano", aliases: ["Rayo Vallecano", "Rayo"] },
  { league: "LALIGA", canonical: "Alaves", aliases: ["Alaves"] },
  { league: "LALIGA", canonical: "Espanyol", aliases: ["Espanyol"] },
  { league: "LALIGA", canonical: "Leganes", aliases: ["Leganes"] },
  { league: "LALIGA", canonical: "Real Valladolid", aliases: ["Valladolid"] },

  // ---------------------------------------------------------------- MLS
  { league: "MLS", canonical: "Atlanta United", aliases: ["Atlanta United"] },
  { league: "MLS", canonical: "Austin FC", aliases: ["Austin FC", "Austin"] },
  { league: "MLS", canonical: "Charlotte FC", aliases: ["Charlotte FC", "Charlotte"] },
  { league: "MLS", canonical: "Chicago Fire", aliases: ["Chicago Fire"] },
  { league: "MLS", canonical: "FC Cincinnati", aliases: ["FC Cincinnati", "Cincinnati"] },
  { league: "MLS", canonical: "Colorado Rapids", aliases: ["Colorado Rapids", "Rapids"] },
  { league: "MLS", canonical: "Columbus Crew", aliases: ["Columbus Crew", "Crew"] },
  { league: "MLS", canonical: "D.C. United", aliases: ["DC United", "D.C. United"] },
  { league: "MLS", canonical: "FC Dallas", aliases: ["FC Dallas"] },
  { league: "MLS", canonical: "Houston Dynamo", aliases: ["Houston Dynamo", "Dynamo"] },
  { league: "MLS", canonical: "Sporting Kansas City", aliases: ["Sporting KC", "Sporting Kansas City"] },
  { league: "MLS", canonical: "LA Galaxy", aliases: ["LA Galaxy", "Galaxy"] },
  { league: "MLS", canonical: "Los Angeles FC", aliases: ["LAFC"] },
  { league: "MLS", canonical: "Inter Miami", aliases: ["Inter Miami"] },
  { league: "MLS", canonical: "Minnesota United", aliases: ["Minnesota United"] },
  { league: "MLS", canonical: "CF Montreal", aliases: ["CF Montreal", "Montreal"] },
  { league: "MLS", canonical: "Nashville SC", aliases: ["Nashville SC", "Nashville"] },
  { league: "MLS", canonical: "New England Revolution", aliases: ["New England Revolution", "Revolution"] },
  { league: "MLS", canonical: "New York City FC", aliases: ["NYCFC", "New York City FC"] },
  { league: "MLS", canonical: "New York Red Bulls", aliases: ["Red Bulls", "New York Red Bulls"] },
  { league: "MLS", canonical: "Orlando City", aliases: ["Orlando City"] },
  { league: "MLS", canonical: "Philadelphia Union", aliases: ["Philadelphia Union", "Union"] },
  { league: "MLS", canonical: "Portland Timbers", aliases: ["Portland Timbers", "Timbers"] },
  { league: "MLS", canonical: "Real Salt Lake", aliases: ["Real Salt Lake", "RSL"] },
  { league: "MLS", canonical: "San Jose Earthquakes", aliases: ["San Jose Earthquakes", "Earthquakes"] },
  { league: "MLS", canonical: "Seattle Sounders", aliases: ["Seattle Sounders", "Sounders"] },
  { league: "MLS", canonical: "St. Louis City", aliases: ["St. Louis City"] },
  { league: "MLS", canonical: "Toronto FC", aliases: ["Toronto FC"] },
  { league: "MLS", canonical: "Vancouver Whitecaps", aliases: ["Vancouver Whitecaps", "Whitecaps"] },

  // ---------------------------------------------------------------- UCL (clubs not already covered above)
  { league: "UCL", canonical: "Bayern Munich", aliases: ["Bayern Munich", "Bayern"] },
  { league: "UCL", canonical: "Borussia Dortmund", aliases: ["Borussia Dortmund", "Dortmund"] },
  { league: "UCL", canonical: "Bayer Leverkusen", aliases: ["Bayer Leverkusen", "Leverkusen"] },
  { league: "UCL", canonical: "RB Leipzig", aliases: ["RB Leipzig", "Leipzig"] },
  { league: "UCL", canonical: "Paris Saint-Germain", aliases: ["PSG", "Paris Saint-Germain"] },
  { league: "UCL", canonical: "Juventus", aliases: ["Juventus", "Juve"] },
  { league: "UCL", canonical: "Inter Milan", aliases: ["Inter Milan", "Inter"] },
  { league: "UCL", canonical: "AC Milan", aliases: ["AC Milan", "Milan"] },
  { league: "UCL", canonical: "Napoli", aliases: ["Napoli"] },
  { league: "UCL", canonical: "Ajax", aliases: ["Ajax"] },
  { league: "UCL", canonical: "PSV Eindhoven", aliases: ["PSV"] },
  { league: "UCL", canonical: "Benfica", aliases: ["Benfica"] },
  { league: "UCL", canonical: "Porto", aliases: ["Porto"] },
  { league: "UCL", canonical: "Sporting CP", aliases: ["Sporting CP", "Sporting Lisbon"] },
  { league: "UCL", canonical: "Shakhtar Donetsk", aliases: ["Shakhtar Donetsk", "Shakhtar"] },
  { league: "UCL", canonical: "Galatasaray", aliases: ["Galatasaray"] },
];
